# Generated by Django 4.2.1 on 2023-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='chat_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
